### PR TITLE
Use handle instead of id

### PR DESCRIPTION
**Pull request by SHoogland**
Section id's can differ between databases, would you be interested in changing this to work based on the sections handle?

If so I will finish this pr with the necessary changes.

### CODE REVIEW

**Comment by reganlawton** [comment]
I'm happy for you to do this change and I can give it a test and if everything checks out I'll be happy to merge it in.

**Comment by SHoogland** [comment]
There we go, this worked for me, let me know what you think.

I also added an 'None' option to the settings, in my case I wanted to disable the related plugin on categories completely.

**Comment by SHoogland** [comment]
The only thing I thought about but didn't have time for yet is adding backwards compatibility, not sure if you would like that?

**Comment by reganlawton** [comment]
Let me test today if this works then we shouldn't need backwards compatibility. If someone comes up with a need for the old way then I'll be happy to add it. Thank you for contributing it's great to see others using the plugin but it's even better to see people actively wanting to update my plugins to make them better.

**Pull request merged**
